import {loadCache,loadMesh} from './cache-loader.js';
import * as THREE from './vendor/three.module.js';
import {OrbitControls} from './vendor/OrbitControls.js';
const $=id=>document.getElementById(id),host=$('view'),scene=new THREE.Scene();scene.background=new THREE.Color('#edf2ed');
const camera=new THREE.PerspectiveCamera(38,1,.01,10000),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));host.prepend(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;
scene.add(new THREE.HemisphereLight(0xffffff,0x71807c,2));const light=new THREE.DirectionalLight(0xffffff,2);light.position.set(5,8,4);scene.add(light);const fill=new THREE.DirectionalLight(0xffffff,.7);fill.position.set(-5,2,-4);scene.add(fill);
new ResizeObserver(()=>{renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix()}).observe(host);
let model,parts=[],data,cache,frameSize=0,time=0,playing=false,speed=1,token=0,center=new THREE.Vector3(),radius=1;const names={Sequence:'起飞 → 飞行 → 降落',LookAround01:'环顾一',LookAround02:'环顾二',Fly:'飞行',TakeOff:'起飞',Land:'降落'};
let fullLoading=false,fullProgress=0;
let poseCenters,poseRadii;
function prepareFraming(){poseCenters=new Float32Array(data.frames*3);poseRadii=new Float32Array(data.frames);let bodyOffset=0,bodyCount=0;for(const part of data.parts){if(part.name==='Red-crownedCrane_Body'){bodyCount=part.vertexCount;break;}bodyOffset+=part.vertexCount*3;}if(!bodyCount){bodyOffset=0;bodyCount=frameSize/3;}let stableRadius=0;for(let frame=0;frame<data.frames;frame++){const sums=[0,0,0];for(let i=0;i<bodyCount*3;i++){const k=i%3,raw=cache[frame*frameSize+bodyOffset+i];sums[k]+=data.encoding==='delta-u16'?data.quantMin[k]+raw/65535*data.quantExtent[k]:raw;}for(let k=0;k<3;k++)poseCenters[frame*3+k]=sums[k]/bodyCount;const lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];for(let i=0;i<frameSize;i++){const k=i%3,raw=cache[frame*frameSize+i],value=data.encoding==='delta-u16'?data.quantMin[k]+raw/65535*data.quantExtent[k]:raw;lo[k]=Math.min(lo[k],value);hi[k]=Math.max(hi[k],value);}let squared=0;for(let k=0;k<3;k++){const extent=Math.max(Math.abs(lo[k]-poseCenters[frame*3+k]),Math.abs(hi[k]-poseCenters[frame*3+k]));squared+=extent**2;}stableRadius=Math.max(stableRadius,Math.sqrt(squared));}poseRadii.fill(Math.max(stableRadius,.001));}
function followPose(a,b,t){for(let k=0;k<3;k++)center.setComponent(k,poseCenters[a*3+k]*(1-t)+poseCenters[b*3+k]*t);model.position.copy(center).negate();radius=poseRadii[0];controls.minDistance=radius*.2;controls.maxDistance=radius*10;}
function fit(view='perspective'){if(!model)return;const vectors={perspective:[1.7,.7,1.8],side:[2.5,0,0],front:[0,0,2.5],top:[0,2.5,.001]};const vertical=THREE.MathUtils.degToRad(camera.fov),horizontal=2*Math.atan(Math.tan(vertical/2)*camera.aspect),distance=radius/Math.sin(Math.min(vertical,horizontal)/2)*1.08;camera.position.copy(new THREE.Vector3(...vectors[view]).normalize().multiplyScalar(distance));controls.target.set(0,0,0);controls.minDistance=radius*.2;controls.maxDistance=radius*10;controls.update()}
function update(){if(!cache)return;const frame=time/data.duration*(data.frames-1),a=Math.floor(frame),b=Math.min(a+1,data.frames-1),t=frame-a;for(const part of parts){const attr=part.mesh.geometry.attributes.position,values=attr.array;for(let i=0;i<part.source.length;i++){const ix=part.offset+part.source[i]*3;for(let k=0;k<3;k++){const value=cache[a*frameSize+ix+k]*(1-t)+cache[b*frameSize+ix+k]*t;values[i*3+k]=data.encoding==='delta-u16'?data.quantMin[k]+value/65535*data.quantExtent[k]:value;}}attr.needsUpdate=true;part.mesh.geometry.computeVertexNormals();}followPose(a,b,t); $('phase').value=time/data.duration;if(data.sequenceStages){const stage=data.sequenceStages.find(s=>time<s.until)||data.sequenceStages.at(-1);document.querySelectorAll('.phase-node').forEach(n=>n.classList.toggle('active',n.textContent===stage.name));$('status').textContent=stage.name;}}
function buildNodes(){const host=$('phaseNodes');host.replaceChildren(...data.sequenceStages.map(stage=>{const button=document.createElement('button');button.className='phase-node';button.textContent=stage.name;button.style.left=(stage.start/data.duration*100)+'%';button.setAttribute('aria-label','定位到'+stage.name);button.onclick=()=>{playing=false;time=stage.start;update();$('play').textContent='播放'};return button;}));}
async function load(mode,autoplay=false,background=false){const id=++token;if(!background)playing=false;if(!background)$('play').disabled=true;if(!background)$('status').textContent='正在加载…';else fullLoading=true;try{const meta=await fetch('crane/'+mode+'.json').then(r=>{if(!r.ok)throw Error('无法加载');return r.json()});const [buffer,animation]=await Promise.all([loadMesh('crane',meta),loadCache('crane',meta,background?(loaded,total)=>{fullProgress=Math.round(loaded/total*100)}:undefined)]);if(id!==token)return;if(background)fullLoading=false;if(model){scene.remove(model);model.traverse(o=>{if(o.isMesh)o.geometry.dispose();if(o.material){o.material.map?.dispose();o.material.normalMap?.dispose();o.material.dispose()}})}data=meta;if(meta.encoding==='delta-u16'){const q=new Uint16Array(animation),stride=meta.parts.reduce((sum,p)=>sum+p.vertexCount*3,0);for(let i=stride;i<q.length;i++)q[i]=(q[i]+q[i-stride])&65535;cache=q;}else cache=new Float32Array(animation);parts=[];frameSize=meta.parts.reduce((s,p)=>s+p.vertexCount*3,0);model=new THREE.Group();const mats={};const loader=new THREE.TextureLoader();for(const m of meta.materials){const mat=new THREE.MeshStandardMaterial({color:m.map?0xffffff:new THREE.Color(...m.color.slice(0,3)),roughness:.85,side:THREE.DoubleSide,alphaTest:m.alpha?.35:0});if(m.map){mat.map=loader.load('crane/'+m.map);mat.map.colorSpace=THREE.SRGBColorSpace;}if(m.normal){mat.normalMap=loader.load('crane/'+m.normal);mat.normalScale.set(.4,.4)}if(m.name.includes('Sclera')){mat.transparent=true;mat.opacity=.08;mat.depthWrite=false;mat.roughness=.1;mat.side=THREE.FrontSide;}mats[m.name]=mat;}
let offset=0;for(const p of meta.parts){const pos=new Float32Array(buffer,p.position.offset,p.position.count),normal=new Float32Array(buffer,p.normal.offset,p.normal.count);for(const sub of p.submeshes){const source=new Uint32Array(buffer,sub.source.offset,sub.source.count),positions=new Float32Array(source.length*3),normals=new Float32Array(source.length*3);source.forEach((vi,i)=>{positions.set(pos.subarray(vi*3,vi*3+3),i*3);normals.set(normal.subarray(vi*3,vi*3+3),i*3)});const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(positions,3));g.setAttribute('normal',new THREE.BufferAttribute(normals,3));g.setAttribute('uv',new THREE.BufferAttribute(new Float32Array(buffer,sub.uv.offset,sub.uv.count),2));g.setIndex(new THREE.BufferAttribute(new Uint32Array(buffer,sub.index.offset,sub.index.count),1));const mesh=new THREE.Mesh(g,mats[sub.material]);mesh.frustumCulled=false;model.add(mesh);parts.push({mesh,source,offset});}offset+=p.vertexCount*3;}
scene.add(model);prepareFraming();radius=poseRadii[0];time=0;update();fit();$('play').disabled=false;$('reset').disabled=false;$('phase').disabled=false;playing=autoplay;$('play').textContent=playing?'暂停':'播放';buildNodes();update();}catch(e){if(background){fullLoading=false;$('status').textContent='预览可用 · 完整动画加载失败';console.error(e);return;}$('status').textContent='此动作仍在准备，请稍后重试';console.error(e)}}
$('play').onclick=()=>{if(!data)return;if(!playing&&time>=data.duration)time=0;playing=!playing;$('play').textContent=playing?'暂停':'播放';update()};
$('reset').onclick=()=>{if(!data)return;playing=false;time=0;update();fit();$('play').textContent='播放'};
$('speed').oninput=e=>{speed=+e.target.value;$('speedText').textContent=speed+'×'};
$('phase').oninput=e=>{if(!data)return;playing=false;time=+e.target.value*data.duration;update();$('play').textContent='播放'};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>fit(b.dataset.view));
let last=performance.now();function tick(now){const dt=Math.min((now-last)/1000,.1);last=now;if(playing&&data){time=(time+dt*speed)%data.duration;update()}if(fullLoading&&data)$('status').textContent='预览播放中 · 完整动画 '+fullProgress+'%';controls.update();renderer.render(scene,camera);requestAnimationFrame(tick)}
requestAnimationFrame(tick);load('Preview',true).then(()=>load('Sequence',true,true));
